FROM node:20.18.0-alpine3.19 AS base

FROM base AS deps

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY ./package*.json ./

RUN npm ci --force

FROM base AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules

COPY ./ ./

RUN npm run build

RUN npm prune --production --force

FROM base AS runner

WORKDIR /app

RUN addgroup --system --gid 1001 nodejs

RUN adduser --system --uid 1001 nextjs

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT=3000

ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
