services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - notask-data:/app/database/volume
    networks:
      - notask-net  

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - notask-net  

volumes:
  notask-data:

networks:
  notask-net:  
    driver: bridge
