services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - sqlite:/app/server/database/volume

volumes:
  sqlite:
